plugin/js/parsers/BakaTsukiParser.js
unitTest/UtestBakaTsukiParser.js

Fixes #27 & #24 
Was supposed to fix #28 by fixing #24 however because the epub readers also treat the novel illustrations as all one page even though pressing down gives you a new image (dafuq) this is unfixable without causing a crap ton of discrepancies between epub readers.
The best way to get rid of the blank page would be to simply add content to it.

Remove blank elements

---

plugin/js/parsers/WuxiaworldCoParser.js

Author's name is not being parsed in the current version and the default value `<unknown>` is being used. I've implemented the extractAuthor function in the WuxiaworldCoParser.js

Parse author name from a series page at wuxiaworld.co

---

plugin/js/parsers/QidianParser.js

webnovel.com shows a title acronym alongside the title of a book. The QidianParser considers the acronym as a part of the title which I find annoying. I have modified the `extractTitleImpl` function to appropriately discard the acronym from the title.

Modified title parsing of QidianParser to discard title acronym

---

package.json
plugin/popup.html
readme.md

This commit expands "selectContentTag" options in user interface with two additional option, main and section. It is not uncommon for website to put main content in main or section tags.

Add main and section options to select content

---

package.json
plugin/js/parsers/FanFictionParser.js
plugin/js/parsers/WLPublishingParser.js

The Information page for fanfiction.net had three problems:
- The 'category' or 'fandom', such as 'Books > Harry Potter' or 'Cartoons > Young Justice' wasn't being included.  Now included.
- Published/Updated times of '19m ago' or '5h ago' aren't useful long term.  Parsed datetimes to string, plus keep hidden seconds-since-epoch attribute.
- URLs in info page where coming out relative to `chrome-extension://<big ID>/...`. Make URLs in info page absolute from document source.
Adding category seemed straight-forward.  I'm not sure that the other changes are done the most 'preferred' way; I considered using `cleanInformationNode()` instead, but it's not really 'cleaning' as such.  If you'd prefer a different approach, please advise me and I'll give it a try.
Keeping the hidden …

fanfiction.net more info (+WLPublishingParser minor fix)

---

eslint/pack.js
package.json
plugin/_locales/en/messages.json
plugin/images/ChapterStateSleeping.svg
plugin/js/ChapterUrlsUI.js
plugin/js/Parser.js
plugin/js/UserPreferences.js
plugin/js/Util.js
plugin/popup.html
readme.md

- Do all existing unit tests pass?  `yes. 570 assertions of 570  passed, 0 failed. (Firefox)`
- Have all warnings and errors reported by eslint been fixed? `yes.`
- If you've added new behavior, Can a user turn it off? Is it off by default? `It's off by default, Accessible in Advanced Options , no reason to throttle if it works normally after all`
- Have you updated the "contributors" section of packages.json with your name? (and ideally email, so I can contact you easily.) `yes`
- Have you updated the "Credits" section of readme.md with your name? `yes`
- Are you committing to the ExperimentalTab branch? `yes`
- Have you rebased your commit?  `no`
Options to Throttle/delay fetching webpage by x seconds/chapter. Accessible via Advanced option (Off by default).
I saw some people in the …

Added Feature: Manual Delay/Chapter (+minor refactor)

---

eslint/pack.js
eslint/release.js
package.json

use as `npm run release` with optional additional args `pre` and `draft`
requires [Github CLI (`gh`)](https://github.com/cli/cli)
- `npm run release` - makes a release on `master` with correct tag `0.0.0.xxx` and with chrome and firefox zips  
provides link to the rease in the end of output
- `npm run release draft` - same, but makes a *draft* of release (should be comfirmed in web to actually create tag and release)
- `npm run release pre` - makes a *pre*release (not displayed as latest in main github page) on `ExperimentalTabMode` branch with tag `0.0.0.xxx.pre-[commit hash]` with zips  
provides link to the rease in the end of output
- `npm run release pre draft` - same, but makes a *draft* of release

add npm release scripts

---

plugin/js/Download.js

This change allows using the extension on Firefox Fenix (the newer "Firefox for Android" browser). 
It seems like the `browser.downloads.download` API isn't implemented yet in Fenix so when it is called nothing happens. No error is thrown but the promise never resolves either. As a workaround I used a temp `a` tag to initiate the download as suggested at [Download File Using JavaScript/jQuery - Stack Overflow](https://stackoverflow.com/questions/3749231/download-file-using-javascript-jquery/9834261#9834261).
I also improved the Android detection using the [`browser.runtime.getPlatformInfo`](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getPlatformInfo) API. This isn't required but it is very useful since it works even when the extension page is opened with …

Fix downloads when using Firefox for Android

---

plugin/js/parsers/KakaoParser.js
plugin/popup.html

This adds the requested parser and closes #639 
Finally had some time. 
Wondering about the alternative to a problem I had. Because all the data was passed to the page through GET calls, I wanted to modify the TOC dom so that when get author, genre, and such was called, it would be able to access the information directly from the api. I didn't see a way to modify that dom. Is there currently no method or is there an alternative I didn't think of? I'll look through the other parsers to see what they did.
This time, the page luckily came with the data pre-javascript execution so I was able to get the data from there.

Implement pagestage.kakao.com Parser

---

plugin/js/EpubMetaInfo.js

After recent updates to iOS and Android, page-break-before causes some weird behavior in some ebook reader.
Specifically, it render an entire blank page on some reader(iOS Book), or break text to speech on some other reader(eink android reader, unknown engine).
I have tested and confirm that it is indeed this tag that causes the issue using Calibre to rebuild the epub.
In most cases, this tag is redundant and alternatively we can try out other method if page break is really required(eg page-break-after on p tag)

Update to H1 H2 CSS

---

eslint/.eslintrc.js
plugin/js/parsers/KakaoParser.js

I was unfortunately forced to learn promises and could no longer chain awaits 😢.
I messed up my git completely and was stuck to commit this fork a few commits behind. For some reason, rebasing, refetching, remerging, hard undoing commits, etc, would not correct the git history to match with ExperimentalTabMode. Thankfully, since it is behind, I was able to pull request just the two commits.
Required to be logged in with a verified account to download PG-15 books.
Closes #648
-----
KNOWN BUGS:
Start on the main page when using WebToEpub. Having ?page=[num] in the url can and will break the rest of the code.
Adding "&& !url.includes("page")" will cause it to break as well. Requires specific if and else cases within wrapFetch to clean URLs. Ugly. Much better to start on main page.
Written on …

Add support for PG-15 chapters from Kakao.com

---

plugin/js/main.js

Fixes #702.
This simply makes the web2epub tab open as a child of the current one, which means it's directly after the current tab, rather than at the end of the tab list.

Open tab as child of current tab

---

plugin/_locales/en/messages.json
plugin/js/Library.js

Bug:
1. Go to https://www.royalroad.com/fiction/11209/the-legend-of-randidly-ghosthound
2. Click WebToEpub
3. Download Chapter 1-813 and Chapter 814-2098 in seperate epubs
4. Click Library -> Check Show Advanced Library Options
5. Click Upload Epub
6. Select the Epub with Chapter 1-813
7. Right click -> Inspect -> Sources -> Library.js
8. Set Breakpoint on line 174 (let content = await zip.generateAsync({ type: "blob", com)
9. Click Add Chapter from different EPUB
10. select the epub with Chapter 814-2098
11. js stops on Breakpoint
12. Press F10
13. js doesn't execute/stops without error
I don't know what was wrong in the old code.

Fixed Library.js LibMergeEpub()

---

package.json
plugin/js/ImageCollector.js
readme.md

Some websites have image path in data-src attribute.
Example:
`<img class="lazyload" data-background="" data-src="https://ranobelib.me/uploads/ranobe/goburin-sureiya/chapters/1843364/7-tom-nacalnye-illyustracii-1_NsIU.jpg" />`

Fix: fixLazyLoadImageSource when image source in data-src attribute

---

plugin/js/parsers/QuestionableQuestingParser.js

Replaced full thread path with basic path to QQ proxy, using regex to replace entire qq path up to proxy.php with the correct path. Somewhat brute-force, but the easiest working solution.

Fix #1112 - Fixed QQ image redirect issue

---

plugin/js/parsers/FanFictionParser.js

Fix for loading inconsistent caching issue on ff.net; automatically checks secondary link upon any failure to retrieve chapter or read chapter text. Separate link calls info directly without interacting with broken caching. Uses existing throttle logic for second call to avoid CloudFlare detection. 
Note: The detection could be narrowed down more to detect page layout and specific error message; This is not done because this method does actually resolve several other rare chapter load issues that have occurred in the last year.

Fix #1118 - Update FanFictionParser.js

---

plugin/js/parsers/KemonopartyParser.js

-fix chapter title to exclude source
-change content selector when the chapter is in text format - removes `<h2>Content</h2>` from every chapter
-remove ads
-get urls of all partial ToC when not all of them are linked in paginator

Fix KemonopartyParser

---

package.json
plugin/js/parsers/SyosetuParser.js
readme.md

-Fixed fetching of chapter urls broken due to introduction of pagination.
-Fixed fetching of author name regardless of author page's existence.

-Fixed broken Syosetu parser

---

plugin/js/parsers/ScribblehubParser.js

Switched FindContent selector to div#chp_raw instead of div#chp_content - it's an inner div that only includes the content of the chapter and author notes.

Fix #1314 - Update ScribblehubParser.js to remove unnecessary fields

---

package.json
plugin/js/parsers/ScribblehubParser.js
readme.md

In addition to the bottom author's note card, ScribbleHub also offers an announcement card (or news) option at the top.
This PR adds it to the `Remove Author Note` option.
Here's an instance of a chapter having it: https://www.scribblehub.com/read/426788-ecdysis/chapter/519798/

Mark scribblehub announcement-card as an author-note

---

plugin/js/parsers/QidianParser.js

Re-added webnovel chapter title. Removed excess links added at bottom of page.

#1342 - Update QidianParser.js for new page style

---

plugin/js/HttpClient.js

This HTTP Error code from Qidian/Webnovel went into hibernation for a while, but it's baaack. Offering handling.

Handle qidian HTTP 445. Effectively acts the same as 500 error.

---

plugin/js/parsers/QidianParser.js

Cleanup output html data, removing unnecessary elements and frivolous metadata. Chapters are visibly the same, but content length reduced by around 50% on average.

Optimize QidianParser.js for smaller files.

---

plugin/js/parsers/TapasParser.js

Changed parse format to json data instead of json body to best access pagination data

#1368 - Update TapasParser for multi-request

---

plugin/js/parsers/RoyalRoadParser.js

Removed random identifier generated className.
Several empty class attributes persist after final output, but should avoid any intentional class removal.

#1375 RoyalRoad Cleanup

---

plugin/_locales/en/messages.json
plugin/js/Parser.js
plugin/js/UserPreferences.js
plugin/js/parsers/69shuParser.js
plugin/js/parsers/FanFictionParser.js
plugin/js/parsers/RanobesParser.js
plugin/js/parsers/ScribblehubParser.js
plugin/js/parsers/Template.js
plugin/popup.html

Implemented logic for a default minimum rate threshold for requests.
Base Parser.js minimum threshold set at null/0ms. 
Implemented default values for Fanfiction, Scribblehub and 69shuParser
As this is a **non-standard** fix across a multitude of files, I will not close this pull request without external approval.
Affected Tickets:
#1377 #1378 #1405 
Ticket numbers are lost in squashes.

#1378   create default parser rate

---

plugin/js/parsers/ScribblehubParser.js

Failed/second Requests on ScribbleHub are common enough to trigger a cloudflare error.

Increase minimumThrottle for ScribbleHub

---

plugin/_locales/en/messages.json
plugin/js/HttpClient.js

If 403 error comes it could be annoying to open the url wich send the warning.
Example pictures are hosted on a different website than the normal contend and sends a 403 warning.
With this change it is one click to open the Webpage and wait until cloudflare etc. is finished -> close tab and confirm cloudflare is clear.

Better 403 handling

---

plugin/js/Parser.js

Example: https://www.scribblehub.com/series/16599/bl-oh-my-fate/
Has 90 requests for Searching for URLs at the moment they are fetcht without slow down.

walkTocPages() add slow down

---

plugin/js/parsers/ChaleuriaParser.js

FIxes #1422.
Normal URL - [https://chaleuria.com/complete-guide-personal-assistant/.](https://chaleuria.com/novels/complete-guide-use-care-personal-assistant/)
Issue - https://chaleuria.com/complete-guide-personal-assistant/
It turns out they provide different toc layout based on URL

#1422 - Fixed ChaleuriaParser

---

.github/workflows/AutoRelease.yml

Related to #1410 
This workflow increases the last Number +1 
Example: 1.0.0.0 -> 1.0.0.1
and pushes the new manifest file in git.
Deletes the old release "Latest developer build" and creates a new one with the right files.

add github workflow

---

.github/workflows/AutoRelease.yml

Added multiple fixes discussed in #1410 
The commit reference in developer-build release is now correct.
The changelog is now correct.
The files are now renamed to .zip
If it is in master branch in actions ui the workflow can be started from hand to bump the version to a real release version witch gets created with placeholder in the notes. (It only works on the ExperimentalTabMode branch)
Abort workflow if there is an error without creating new release.

auto release set to only execute if branch is ExperimentalTabMode

---

.github/workflows/AutoRelease.yml

The link to view Changelog points at the moment to 0.0.0.160 instead of 0.0.0.167
If the next release increases another version number than the dev version number e.g. 0.0.1.0 no manual fix is needed.
Why?
The logic just sets the dev number to 0 and compares this tag with the current developer-build.
If the old tag is 0.0.0.0 than it gets replaced with 0.0.0.167 as exception.
reference: #1410

fix_changelog_from_tag

---

plugin/js/HttpClient.js

I hope this fixes #1444
Problem:
On fanfiction.net
parsedUrl.hostname is www.fanfiction.net but the "domain" is .fanfiction.net
if www. is striped from the hostname it matches the cookies.

fix_www_subdomain_cookie_issue

---

plugin/js/parsers/PatreonParser.js

Patreon collections changed again (I guess...).
This collects all loaded post links from a collection using a nested h3 as discriminator (this is the title of the card), there's no data-tag attributes anymore on the collection page

Fix Patreon Collections

---

plugin/js/HttpClient.js

reference: #1447
firefox added [CHIPS](https://developer.mozilla.org/en-US/docs/Web/Privacy/Privacy_sandbox/Partitioned_cookies) support in Nightly build.
The fix is backwards [compatible](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/getAll) with firefox > 94.0
No need to change min firefox version in manifest.json
Tested with:
https://mtlarchive.com/novel/traveling-through-thousands-of-realms-starting-from-obtaining-the-ten-marvel-rings
Firefox version 130.0 (64-bit)
Firefox version 132.0a1 (2024-09-06) (64-bit)
Google Chrome Version 128.0.6613.115

Add CHIPS cookie state to firefox (cloudflare)

---

plugin/js/parsers/GenesiStudioParser.js
plugin/js/parsers/Template.js
plugin/popup.html

@dteviot reference: #1423
I have a problem:
I set the Chapterlist links to the api links e.g.: [https://genesistudio.com/viewer/6213/__data.json](https://genesistudio.com/viewer/6213/__data.json)
and in findContent() i want to extract the content from the json response but at the moment it fails i think the problem is that it is not valid html is there a solution for this problem?
A "hack" would be i set the links in Chapterlist to a valid HTML page e.g. [https://genesistudio.com/viewer/6213](https://genesistudio.com/viewer/6213) and than in the function findContent() 
`let data = (await HttpClient.fetchJson(dom.baseURI + "/__data.json")).json;`
but i don't think this is the right approach.

Add genesi studio parser

---

plugin/js/HttpClient.js
plugin/js/parsers/SpacebattlesParser.js

Previous logic attempted to duplicate cookies which were being set by default within chrome's request object. Cookies at issue had specialized settings of "Session" or no_restriction on SameSite.
@gamebeaker - I'd like your opinion on the HttpClient change before pushing it through; under the current build, if you open the chrome dev console while running on a site like fanfiction.net, you can see the number of errors popping up. The errors don't actually break anything, but they do make debugging other things a tad annoying. 
I'm fairly confident it covers all situations for your former fix, but I'd like to know if there's any glaring issues or if you think the filter should be handled from a different angle.
To no one in particular: SpacebattlesParser change is more of an irregularity …

Reduce http header cookie clutter

---

plugin/_locales/en/messages.json
plugin/js/Library.js
plugin/js/main.js
plugin/js/parsers/GenesiStudioParser.js
plugin/popup.html

@Kiradien related to #1365 #1365
I changed how the Readinglist gets updated if the book is deleted. 
Why?
If you open WebToEpub from a not valid page example in 
chrome: `chrome://extensions/`
firefox: `about:addons`
It wasn't possible to delete a epub.
Additionally i added the deletion of the reading list of the saved books if the Library gets cleared with "Clear Library".
Is that ok or did you have other reason to use .addObserver(library)?
Now the original commit:
Allow the user to export/ import the current Library with reading status as json file.
minor fix: the save as dialog got triggered if "Add to Library" is used on a new url -> now only triggers if the Option "Download Epubs after new Chapter got added automatically" is checked.

Library export import function

---

plugin/_locales/en/messages.json
plugin/js/ErrorLog.js
plugin/js/HttpClient.js
plugin/popup.html

reference: #1491, #1488, #1361
Added option to block URL.hostname from an 403 error URL. 
This can reduce the ammount of errors an user has to skip if the images on the website are now 403 like on patreon.
Changed 403 handling for the user.
Old:
New:
Only one error page.

Change 403 user options/ handling

---

plugin/js/Library.js

Double render speed of Library.
The more Bytes are saved in chrome.storage.local or the Library the slower the rendering is.
With the reduction from 2 calls of chrome.storage.local.get() to 1 it is double the speed.

speedup Library.LibRenderSavedEpubs()

---

.gitignore
package.json
plugin/js/parsers/MagicWizardsParser.js
plugin/popup.html
readme.md

WIP. Add parser for mtgstory.com (redirects to https://magic.wizards.com/en/story). Seems to work on most versions of the website (e.g. current live version, archive.org version from 2-3 years ago, untested on 10 years ago archive.org version). Still missing fallback support for mtglore.com. 
Based on MagicWizardsParser.js v0.6 from https://github.com/Darthagnon/web2epub-tidy-script

Add parser for mtgstory.com

---

plugin/js/Parser.js
plugin/js/Util.js

reference: #1455
To use the change add this to the Stylesheet:
```
.WebToEpub-table {
border-collapse: collapse;
width: 100%;
}
.WebToEpub-row {
display: flex;
border: 1px solid black;
}
.WebToEpub-cell {
flex: 1;
padding: 5px;
border: 1px solid black;
}
```
@dteviot as this is really obscure i would appreciate other ideas to enable this option.
Maybe a new Checkbox "tolino compatibility"?.
Why not always convert tables to div?
It looks like only tolino has the problem and not other reader. As the table looks better than the div version other user shouldn't be impacted from the tolino fix.
Tested with:
https://www.royalroad.com/fiction/22546/inexorable-chaos-complete/chapter/324087/chapter-four-abnormal-summoning
There is a table in a table and the table is to long for tolino.

Create convertTableToDiv to fix royalroad tables on tolino

---

plugin/js/parsers/XenforoBatchParser.js
plugin/popup.html

New Manual parser for xenforo forums; downloads all posts across multiple pages - resolves ticket #1454

#1454 xenforo batch post dl

---

plugin/_locales/en/messages.json
plugin/js/ChapterUrlsUI.js
plugin/js/DefaultParserUI.js
plugin/js/Parser.js
plugin/popup.html

reference:  #1452
"Edit Chapter URLs" accepts now pure URLs (one URL per line)
The title name is `[placeholder]` if the parser has implemented `findChapterTitle()` this name is used if `findChapterTitle()` isn't implemented `dom.title` gets used.
Problem:
You have to know that you can simple paste an URLs list. (no hint etc,)
@Darthagnon any ideas how to inform the users?

Improve edit chapter urls

---

package.json
plugin/js/parsers/MtlnovelsParser.js
plugin/popup.html
readme.md

Closes #1545 
I've added a new script and changed the way it fetches the chapters from MTLNovels, as of now they are not giving back the urls in a json anymore. Now the scripts scrapes the chapter list url and gets all the chapters from it.  
I've tested it and it works (for me), as specified in contributing all the tests pass, I've also added my name to the contributors list.  
Let me know if there are any further changes or tests that I need to make. By the way, thank you for your work, it's an amazing idea.

Added MTLNovels support

---

plugin/manifest.json

reference: #1576
https://developer.mozilla.org/en-US/docs/Web/API/URL/canParse_static
@dteviot In manifest.json the "minimum_chrome_version" and "strict_min_version" got changed. This would be a "majore" release if the versioning is as described here #1515.

increase min browser version URL.canParse()

---

plugin/js/parsers/MvlempyrParser.js
plugin/popup.html

Solves Issue #1568 
One of the weirdest sites.
Notes:
1. Each Novel has a slug which is used to get the Novel Id, Chapter Count but don't know from where slug is being created. Had to take the slug from image source. This api call sometimes fail. So, had to use again chapter count div to get it
2. API call to get Chapter URL always give 404 for some reason. No time to check.
API Call to get ID : 	https://chp.mvlempyr.net/wp-json/wp/v2/tags?slug=6062 => {"id": 2021, "count": 190} and more
API Call to get Chapters : https://chp.mvlempyr.net/wp-json/wp/v2/posts?tags=2021&per_page=500&page=1 => Gives JSON error
@dteviot can you check
Code is working fine but is there any better implementations?

Add Site mvlempyr

---

package.json
plugin/js/parsers/WxscsPaser.js
plugin/popup.html
readme.md

This addresses this issue:
https://github.com/dteviot/WebToEpub/issues/1619
It adds support for https://www.wxscs.com with multi-page support.
I used WattpadParser as a reference since it was the only one I could find that supported multi-page.
I'm continually impressed with Claude Sonnet, I gave it about 2 dozen parsers, top/bottom 12 based on size, asked it if anything had multi-page support, had a discussion on how it worked, gave it the html for the index and a random 3 page chapter, and it one shot a completely working extension.  I've been a dev for 20 years, and it blows my mind every time I do something like this.
I tested it out on a few books on the site, worked great.

Add Site wxscs.com

---

.github/workflows/node.js.yml

fixes #1663 
@dteviot i just removed the actions/upload-artifact as it isn't needed as the releases get created with [AutoRelease.yml](https://github.com/dteviot/WebToEpub/blob/ExperimentalTabMode/.github/workflows/AutoRelease.yml)

fix github actions

---

plugin/js/Library.js

As the api for zip.js is different than jszip it is easier this way and as it is the 1 zip export version i won't have the make a different logic for version 1 and 2.

update Libexport for zip.js logic

---

plugin/js/Library.js

reference: #1724
Firefox designated the wrong content type on file upload and handled not found in local storage different than chrome.

Fix Firefox Upload EPUBs to Library

---

plugin/js/Library.js

In #1720 the error handling got improved.
A side effect is that should some fields not be populated with new data the old data is still in the field.
To fix this all data will be cleared from all fields before a new Library search is initiated.

Library clear fields before new search

---

package.json
plugin/js/parsers/MarxistsCNParser.js
plugin/popup.html
readme.md

- Adding new script `MarxistsCNParser.js` into `plugin/js/parsers/`.
- Adding one line in `popup.html` correspondingly. 
- Adding myself into `package.json`and `Credits`.
Currently, only works on pages have an index page. For example:
```
https://www.marxists.org/chinese/emma-goldman/1910/index.htm
https://www.marxists.org/chinese/bukharin/1917/index.htm
https://www.marxists.org/chinese/rosa-luxemburg/1898/index.htm
```
The output epub file is complete and clean.

Adding new parser for marxists.org support

---

plugin/js/parsers/WtrlabParser.js

#1430 wtr-lab now has AI translation which is causing the download failure.
Issues not resolved by this PR:
- wtr-lab also support other free translation services like Bing and Sogou, a user might want the option to chose between these services. Allow this in advanced config?
- Since wtr-lab seems to do the translation on demand, if the chapter is not already translated  WebToEpub  would still fail.

Update WtrlabParser.js to always use google for translation

---

plugin/js/Library.js

This adds an Array that stores the ids under which the epubs are stored locally.
This helps to speed up the rendering of a large Library.
Comparison with the same Library:
old:
new:
It is subjectively even faster as the it renders the Library with empty placeholdern before they get populated (like youtube).

Library speedup render

---

plugin/_locales/en/messages.json
plugin/js/Library.js
plugin/popup.html

The only reason for "Search new Chapters" to exist was that the Chapter search wasn't async with Update all this got implemented. If someone uses "Search new Chapters" he will click "Add to Library" after that. This is now one click.

Library change SearchNewChapter to Update

---

plugin/js/parsers/WanderinginnParser.js

Wandering inn parser will now call the "removeNextAndPreviousChapterHyperLinks" method to remove the unneeded next and previous hyperlinks. (This also removes the large white spaces in between chapters)
Before:
After:

Updated WanderingInnParser.js

---

plugin/_locales/en/messages.json
plugin/js/UserPreferences.js
plugin/js/parsers/QidianParser.js
plugin/popup.html

@Kiradien in reference to #1778 and #1775
My idea is a little different from yours.
I added this Checkbox 
And my Idea is that the Chapter title in the content gets always replaced with the title from the ToC in case there is [placeholder] your fix from #1778 will be used.
I am going to be honest and say that i didn't really understand your regex i tried it here https://regex101.com/ and couldn't get it to work with problematic title (example: `Chapter 1: Chapter: 1`)
To be honest i am surprised that this isn't already the norm. Now that i think about it this would make `findChapterTitle()` for all parser irrelevant if always the ToC name would be used.

potential fix #1775

---

plugin/js/Library.js

The first time LibBytesInUse() gets executed in a browser session it takes chrome a while before it returns a result which slows down the rendering.

speedup Library first render

---

plugin/js/Library.js

I moved the "Library uses" info in the advanced Library options menu as the normal user doesn't care about it.

Library move Bytes used

---

plugin/js/Library.js

This fixes an error with update all
If the 1st epub is still merging when the 2nd epub tries to merge there are multiple errors:
This pull request should fix this problem.
Additionally there is a problem with the EventListeners in the Library (If an exported library gets imported the eventlisteners don't get removed)
This pull request should fix this problem.

Library fix errors

---

plugin/js/HttpClient.js
plugin/js/parsers/EstarParser.js
plugin/manifest.json
plugin/popup.html

reference: #1770
@dteviot please confirm merge it could be that this triggers a manual review as a new permission is needed for the change
`declarativeNetRequest`
What is the problem?
Some sites check the headers they receive and only send content if the headers are correct.
estar.jp for example checks if the "origin" header is correct if it exists.
With this change i created a rule that removes the "origin" header from all requests.
This could also be used for other sites such as wtr-lab.com #1847 as they changed to a "POST" api which checks these headers.
I created it in HttpClient.js to try and abstract the security concerns.
declarativeNetRequest rules are pretty powerful and can compromise the security on other sites if they aren't bound to WebToEpub only.

Add declarativeNetRequest header handling

---

plugin/_locales/en/messages.json
plugin/css/default.css
plugin/js/Parser.js
plugin/js/UserPreferences.js
plugin/js/parsers/AlphapolisParser.js
plugin/js/parsers/BabelChainParser.js
plugin/js/parsers/ComrademaoParser.js
plugin/js/parsers/FanFicParadiseParser.js
plugin/js/parsers/GenesiStudioParser.js
plugin/js/parsers/LightNovelBastionParser.js
plugin/js/parsers/LightNovelWorldParser.js
plugin/js/parsers/NobadnovelParser.js
plugin/js/parsers/NoblemtlParser.js
plugin/js/parsers/RanobesParser.js
plugin/js/parsers/RoyalRoadParser.js
plugin/js/parsers/SpacebattlesParser.js
plugin/js/parsers/Template.js
plugin/js/parsers/WattpadParser.js
plugin/js/parsers/WtrlabParser.js
plugin/js/parsers/XenforoBatchParser.js
plugin/popup.html

reference: #1468
this change sets the clampSimultanousFetchSize() for all to 1 and removes the option to increase it from the user.
It sets minimumThrottle=500 in the Parser constructor for all parsers.
The ms delay is now a input field instead of a selection.
I am not sure if removing the option for simultanous fetch is the right move. Thoughts @dteviot @Kiradien?

update speed logic

---

plugin/js/Library.js

Should a epub be to big LibConvertDataUrlToBlob() falls back to another method and this sets the mime type wrong.
Example: add https://www.royalroad.com/fiction/64223/dungeon-diver-stealing-a-monsters-power to the library with all the pictures. -> unable to download the epub from the Library.

fix Library LibConvertDataUrlToBlob() for large epubs

---

plugin/js/HttpClient.js
plugin/js/Parser.js
plugin/js/parsers/SangtacvietParser.js
plugin/js/parsers/WtrlabParser.js

reference: #1874
This adds two functions to the Parsers:
isCustomError()
take a look at the content and decide if it is really HTTP 200 (true=error; false=success)
setCustomErrorResponse() 
this function manipulates the response so that it is handled like an HTTP error
To make use of this the parser needs to be added to the "fetchOptions" or "wrapOptions".
I changed two parser that make use of this:
SangtacvietParser
It returns HTTP 200 but the json body doesn't contain the content.
WtrlabParser
If it is the first time someone requests a page the server returns HTTP 200 with missing content while the server is translating the content with the custom HTTP 999 error it is possible to set parser specific retry delay times.

Add custom retry error

---

plugin/js/parsers/ScribblehubParser.js

scribblehub.com doesn't rate limit walkTocPages() only the download of the chapters.

update ScribblehubParser speedup walkTocPages

---

plugin/js/Parser.js
plugin/js/Util.js
plugin/js/parsers/NovelinguaParser.js
plugin/js/parsers/TapasParser.js

I'm know I'm an outlier who edits every epub I touch, but it's nice not to see (and clean up) a ton of completely pointless spans. I also used to see style="" or class="" sometimes.
Plus some other clean up, a couple new util functions that can reduce lines of code elsewhere, and improvements to the TapasParser as I've been using it.

Fewer empty things in epub

---

plugin/_locales/en/messages.json
plugin/css/default.css
plugin/images/FileEarmarkCheck.svg
plugin/images/FileEarmarkCheckFill.svg
plugin/js/ChapterUrlsUI.js
plugin/js/ReadingList.js

The main goal of this PR is to add an icon (and tooltip) to help understand what is going on with the reading list, library, why things start out unchecked when you use them and what is going to be updated if you click "Add to Library" again.
I very much want to cache chapters downloaded and I read in a comment on an issue that the library kind of serves that purpose. But I couldn't understand how the library worked until I actually read the code and learned there was a reading list option and it was involved.
I still think there's more I want to do with caching that the library doesn't quite cover, but adding the icon for Previously downloaded chapters feels like step in the right direction to know what is even in the Library books.
Other changes in this PR are just because of fixes for …

Update download state icons and add tooltips

---

plugin/_locales/en/messages.json
plugin/js/ImageCollector.js
plugin/js/UserPreferences.js
plugin/popup.html

- Added checkbox to choose to compress images
- Added field to choose maximum resolution (height/width)
- Passed image object generated to get image dimensions back for secondary usage
- Replaced image from arraybuffer to converted jpeg
Code has one flaw - the last chapters encoded may not be fully compressed. Images still remain, however at full size. Any suggestions to resolve the async issue would be appreciated.

Add image compression logic
