dteviot/WebToEpub

plugin/js/EpubPacker.js, plugin/manifest.json, readme.md
Pull request to add the enhancement #6
=> Firefox Support with WebExtensions

plugin/js/parsers/GutenbergDEParser.js, plugin/popup.html
my poor contribution to this great tool.. adding epub functionality to license free german books
=> new parser for German Gutenberg Projekt

plugin/_locales/ru/messages.json
=> Russian localization

plugin/js/parsers/BabelChainParser.js
My small fix which made BabelChain work but requires probably some styling as content is returned in blackquote so its unformated...
=> Trying to fix BabelChain

package.json, plugin/js/parsers/AlphapolisParser.js, plugin/js/parsers/NovicetranslationsParser.js, plugin/popup.html, readme.md
issues #467
Alphapolisparser problem:
chapter titel are pretty long because they contain date of creation and word count.
issues #468
Novicetranslations problem:
gets too many chapterlinks (first few) because bad class selector.
=> Alphapolis, Novicetranslations parser

eslint/.eslintrc.js, plugin/_locales/en/messages.json, plugin/js/EpubMetaInfo.js, plugin/js/Parser.js, plugin/js/UserPreferences.js, plugin/js/main.js, plugin/js/parsers/GunnerkriggParser.js, plugin/js/parsers/MadaraParser.js, plugin/js/parsers/RoyalRoadParser.js, plugin/js/parsers/Template.js, plugin/popup.html, readme.md
In .eslint.js : I changed "ecmaVersion": 8->2019 because i got an error with try{}catch{} and here eslint/eslint#13838 they suggested using 2019.
Minor fix Additional Metadata description.
Minor fix layout from Throttle/ Delay.
Added Author from Additional Metadata if 'unknown'.
Added possibility to populate Additional Metadata in parser/ template.
Added Additional Metadata in parser RoyalRoad and Madara.
Added auto search function for Additional Metadata.
=> Additional Metadata auto search

plugin/js/parsers/ReadLightNovelParser.js
This removes everything that I noticed
=> Remove more junk from https://readlightnovel.org/

package.json, plugin/js/parsers/FreeWebNovelParser.js, plugin/popup.html, readme.md
I'm not a expert on javascript so had a hard time getting the lint to work properly. When i tried to do the 'npm install' on the project I got an error ' No matching version found for qunit@1.19.0'. So this code is not lint checked as i could not get it to work. I have however gotten the novel I wanted to epub to work. So the code works as intended.
=> Add site freewebnovel.com

package.json, plugin/js/parsers/CClawTranslationsParser.js, plugin/popup.html, readme.md
- Passed the unit tests using Chrome. I don't have Firefox, so I didn't check for that browser.
- Checked using eslint. No error reported.
- Tried using packed extensions on Chrome. No problem. Work as expected for CClaw Translations Parser.
- Added name to package.json and readme.md.
=> Add site https://cclawtranslations.home.blog

plugin/js/parsers/LightNovelWorldParser.js
The site configuration for LightNovelWorld and LightNovelPub has changed and requires a separate pageload to show chapter information. Chapters are no longer determined through searchParams and need a defined path.
POST methodology no longer works to request paging, however default setting GET requests work fine.
Changed cover search logic to default to og:image meta data for book cover before the standard utility "FirstImgSrc".
isWatermark logic changed to search for classname since the site formatting only uses classes inside the content area for watermarks and Advertisements. Old Inclusion logic often failed when spaces were applied to the watermark (Fairly common on several hundred chapter stories.) This can be safely/easily reverted and still work most of the time.
=> Update LightNovelWorldParser.js to function with new site structure

package.json, plugin/_locales/en/messages.json, plugin/_locales/ru/messages.json, plugin/_locales/uk/messages.json, plugin/_locales/vi/messages.json, plugin/js/Download.js, plugin/js/UserPreferences.js, plugin/js/main.js, plugin/popup.html, readme.md
I think this works, but I just learned Javascript a few moments ago. It was fun though. Eventually want to try more sometime. Also want to try my hand at making a parser, but have to find a website first. Was wondering why my locale variable text wasn't changing in the unpacked extension, but compiling it with eslint worked. 
Hopefully resolves #523, but I want to try adding an actual download button and maybe a hacky way to select a default download folder, though on what I've read, that doesn't seem to be possible because _security_. Read through the documentation for the Download API. 
Note to self: 
https://browser-fs-access.glitch.me/
https://github.com/GoogleChromeLabs/browser-fs-access#opening-directories
Quick note, I don't know the other three languages at all, so they are …
=> Add background download option

.github/workflows/node.js.yml
github action, fixed for it to build only on `ExperimentalTabMode` branch and removed packed.js
=> Github Action

plugin/_locales/en/messages.json, plugin/css/default.css, plugin/js/Library.js, plugin/js/UserPreferences.js, plugin/js/main.js, plugin/manifest.json, plugin/popup.html, readme.md
Function mentioned in #812 it makes use of the feature "Readinglist".
Firefox error getBytesInUse() for local storage.
Bug is known https://bugzilla.mozilla.org/show_bug.cgi?id=1385832
Help needed:
UI (doesn't look nice)
"Search new Chapter" doesn't work for all websites ([www.webnovel.com](http://www.webnovel.com/))
=> Add Library Function.

plugin/js/Library.js, plugin/js/main.js
Fix firefox android bug #936 
Fix mozilla warnings #933
=> Fix firefox adroid bug and mozilla warnings 

package.json, plugin/js/parsers/LiteroticaParser.js, readme.md, unitTest/UtestLiteroticaParser.js
Added capability to pull from Top Lists and Categories.
Fixed selectors for article list and series page.
=> fixed literotica.com

plugin/js/parsers/LiteroticaParser.js
This fixes the members page chapters not working.
=> Fix member page chapters

plugin/js/parsers/NovelUsbParser.js, plugin/popup.html, readme.md
Created parser for novelusb.com in plugins->js->parsers
Updated popup.html with link
Updated readme with contributers name
=> Parser for Novelusb.com

plugin/js/parsers/LightnovelreaderParser.js
=> Updated parser to include lnreader.org

plugin/js/parsers/NovelUsbParser.js
Add site novelbin.me in novelusb parser
Solves issue #1039
=> Add site www.novelbin.me

plugin/js/parsers/ReadwnParser.js
Add site www.wuxiap.com in readwn parser 
Solves issue #1042
=> Add site www.wuxiap.com

package.json, plugin/js/parsers/MtlnovelParser.js, readme.md
=> Add author extract for mtl novel

package.json, plugin/_locales/en/messages.json, readme.md
=> Fix #1077: typo in messages.json

plugin/js/parsers/NovelfullParser.js
Add readnovelfull.me into novelfull parser
=> Add readnovelfull.me

plugin/js/parsers/ReadwnParser.js
Registered wuxiabee as a relevant target for ReadwnParser
Update ReadwnParser.js
=> Fix #1121 - Add wuxiabee to readwn parser

plugin/js/parsers/NovelfullParser.js
Add novel-bin.com in novelfull parser
=> Add novel-bin.com in novelfull parser

plugin/js/parsers/KemonopartyParser.js
Fixes #1168 for KemonopartyParser
=> KemonopartyParser don't download unwanted images

plugin/js/parsers/CyborgParser.js, plugin/popup.html
Add Site www.cyborg-tl.com
- Create Parser CyborgParser.js in js/parsers
- Add src in popup.html
=> Add Site www.cyborg-tl.com

plugin/js/parsers/NovelfullParser.js
=> Add Site noveltrust.net

plugin/js/parsers/ExiledrebelsscanlationsParser.js
Solves Issue #1195 for exiledrebelsscanlations Parser
=> Fix Parser exiledrebelsscanlations

plugin/js/parsers/GravityNovelsParser.js, plugin/popup.html
Solves Issue #1222 
Created New Parser -> GravityNovelsParser.js
Add Parser in popuop.html
=> Add Site gravitynovels.com

plugin/js/parsers/ReadwnParser.js
=> Add Site fannovels.com

plugin/js/parsers/NoblemtlParser.js
=> Add Site daotranslate.us

plugin/js/parsers/SpacebattlesParser.js
Solves Issue #1237 
Issue -
Some Chapter url hash is empty
Tested on -
- https://forums.sufficientvelocity.com/threads/philosophers-tinker-worm.127516/
- https://forums.sufficientvelocity.com/threads/a-flung-light-worm-minor-toaru-cross.124037/
=> Repair SpacebattlesParser

plugin/js/parsers/NovelfullParser.js
=> Add Site novelactive.org

plugin/js/parsers/SyosetuParser.js
-Added method for fetching info page
-Added methods for processing info data
=> Updated SyosetuParser.js to resolve issue #1210

plugin/js/parsers/NovelonomiconParser.js
Parsing the cover image is still broke, but not sure how to fix it.
=> Get Novelonomicon working again.

plugin/js/parsers/TapasParser.js
-Fixes fetching chapter urls on Tapas.io
-Fixes fetching info page description on Tapas.io
=> Fixes #1242

plugin/js/parsers/ReadwnParser.js
=> Add Site wuxiaspot.com

plugin/js/parsers/NovelfullParser.js
=> Add Site topnovelfull.com

plugin/js/parsers/NoblemtlParser.js
Added cyborgtl to NoblemtlParser.
=> #1336 - Add cyborg-tl.com

plugin/js/parsers/ChaleuriaParser.js
Bugfix to handle multiple page formats used by paid content.
=> #1346 - Update ChaleuriaParser.js to handle multiple formats

plugin/js/Library.js, plugin/js/ReadingList.js, plugin/js/main.js
- Added userpreferences to Library
- Added try-delete to readingList with boolean return value should status be required.
- called readingList through userPreferences object in Library
=> #1365 - Update readinglist when removing epub

plugin/js/parsers/ScribblehubParser.js
Fixes https://github.com/dteviot/WebToEpub/issues/1373
=> Fix information page extraction. 

plugin/js/parsers/FreeWebNovelParser.js, plugin/js/parsers/NovelfullParser.js
Updated FreeWebNovelParser
Update NovelfullParser
=> #1377 - Set minimumThreshold for NovelFull, NovelBin and FreeWebNovel

plugin/js/parsers/NovelsemperorParser.js
=> Add Site novelsemperor.net

plugin/js/parsers/Booktoki152Parser.js, plugin/js/parsers/MtlarchiveParser.js, plugin/js/parsers/QidianParser.js, plugin/js/parsers/ReadwnParser.js
Resolves tickets 
#1433 
#1432
=> Set minthrottle for multiple parsers

.github/workflows/AutoRelease.yml
changes:
majore -> major
minore -> minor
=> fix_typo in workflow

plugin/js/HttpClient.js
=> fix_chrome_cookie_bug

plugin/js/HttpClient.js
=> set_cookie_domain_to_highest_domain

plugin/js/parsers/SystemTranslationParser.js
=> update systemtranslation parser

plugin/js/parsers/MtlarchiveParser.js
=> add fictionzone.net to MtlarchiveParser.js

plugin/js/parsers/FreeWebNovelParser.js
=> Add novellive.app to FreeWebNovelParser

plugin/js/parsers/GenesiStudioParser.js
The hash value looks pretty random could be that it gets changed regularly.
If that is the case new logic to extract content.
=> Fix genesi studio parser

plugin/js/Library.js, plugin/js/main.js
related: #1503
@Kiradien your solution was better.
i had consistency issues with the reading list and with addObserver() it is now consistent.
=> Library fix readinglist

.gitignore, plugin/js/parsers/Book18Parser.js, plugin/popup.html
=> Add Book18Parser

plugin/js/parsers/FanFicParadiseParser.js, plugin/popup.html
reference: #1533
looks like SpacebattlesParser with changes.
tested url: https://www.fanficparadise.com/fpforum-sfw/index.php?threads/testing-the-threadmarks.26/#post-32
=> Add FanFicParser

plugin/js/Parser.js, plugin/js/Util.js
This reverts commit 4a400f998532e4a338189cb818c9c11d901b54b5.
reference: #1516 
@dteviot i think you are right that this should be in EpubEditor and not in WebToEpub.
I created a pull request for EpubEditor https://github.com/dteviot/EpubEditor/pull/9
@dteviot please merge this pull request after https://github.com/dteviot/EpubEditor/pull/9 got merged.
=> Revert "Create convertTableToDiv to fix royalroad tables on tolino"

plugin/js/parsers/StorySeedlingParser.js
Update StorySeedling image attribute
=> Update StorySeedling image attribute

plugin/js/parsers/LightNovelWorldParser.js
=> Add Site novelbob.org

plugin/js/parsers/LightNovelWorldParser.js
=> Add Site novelfire.net

plugin/js/parsers/ReadindpiaParser.js, plugin/popup.html
=> Add Parser Readingpia

plugin/js/parsers/NovelsOnlineParser.js, plugin/popup.html
=> Add Site novelsonline.net

plugin/js/parsers/MoonDaisyParser.js, plugin/popup.html
=> Add Site MoonDaisy

plugin/js/Library.js
reference: #1685
@dteviot how long should the logic to import old export files be kept?
=> Library update Export/ Import to zip archive

plugin/js/Library.js
reference: #1679
I don't know why this fix works. 
It should not be different than before.
=> Fix update Library metadata

plugin/js/Library.js
=> Fix Library EPUB 3

plugin/js/parsers/SmeraldoGardenParser.js, plugin/popup.html
=> Add Site smeraldogarden.com

.github/workflows/AutoRelease.yml
=> fix developer build instructions link

plugin/js/parsers/FanFictionParser.js
Updated minimal throttle to account for slightly faster computers & connections making requests at min accepted threshold. Updated failure regex to account for secondary failure condition Created secondary forwarding condition.
Updated fetchWebPageContent method to proper recursion instead of invoking super
=> #1701 Update FanFictionParser.js

eslint/.eslintrc.js, plugin/_locales/en/messages.json, plugin/js/Library.js, plugin/js/Parser.js, plugin/js/main.js, plugin/popup.html
reference: #1581 
This adds an button which tries to update all books in the Library and adds an indication if new Chapter got downloaded.
To realize this i added Promises to multiple functions to know when the TOC is fully loaded/ The EPUB finished downloading.
@dteviot do you know of an more elegant way or is this ok?
I also changed an eslint rule "no-async-promise-executor":0
=> Add Library update all

plugin/js/EpubPacker.js, plugin/js/Library.js
=> Fix mimetype compression

plugin/js/EpubPacker.js, plugin/js/Library.js
=> Fix mimetype extendedTimestamp

eslint/.eslintrc.js, package.json, plugin/js/ErrorLog.js, plugin/js/Library.js, plugin/js/main.js
reference: #1717 #1715
It should help in the case metadata can't be found but the chapter list can be created.
@dteviot I increased the eslint version as version 7 doesn't support static variables in classes.
=> Update library search new chapter

plugin/js/ReadingList.js
=> Fix readinglist interrupted download

plugin/js/ChapterUrlsUI.js
reference: #1553 #1486
Changes popup trigger from Chapter tabel to Checkboxes specific.
=> Fix multi-selection popup

plugin/_locales/en/messages.json, plugin/js/Download.js, plugin/js/UserPreferences.js, plugin/js/main.js, plugin/popup.html
reference: #810
Added Custom Filename option:
https://github.com/dteviot/WebToEpub/wiki/Advanced-Options#custom-filename
=>  Add customizable filename

plugin/_locales/en/messages.json, plugin/js/UserPreferences.js, plugin/js/main.js, plugin/popup.html
reference:#1731
It also fixes eslint warnings:
[xmldom warning]        attribute "hidden" missed value!
=> Add more Metadata options

plugin/js/parsers/MvlempyrParser.js
Add extractSubject to the MvlempyrParser
=> update MvlempyrParser extractSubject

plugin/js/Library.js
Allows the reordering of the EPUBs in the Library 
Adds the reordering buttons under "Show Advanced Library Options"
=> Library change order

.github/workflows/AutoRelease.yml
=> Change Release message

plugin/js/Parser.js, plugin/js/main.js, plugin/js/parsers/DaoDivineTlParser.js, plugin/js/parsers/Template.js, plugin/popup.html
reference: #1519
@dteviot any thoughts?
=> Add async loadEpubMetaInfo()

plugin/js/parsers/NovelsquareParser.js, plugin/popup.html
=> Add NovelsquareParser

plugin/js/ProgressBar.js
reference: #1783
shows the progress as % with one decimal
=> Show progress in tab title

plugin/_locales/en/messages.json, plugin/js/EpubMetaInfo.js, plugin/js/main.js
the search link changed for novelupdates.com and wlnupdates doesn't exist anymore. `https://github.com/fake-name/wlnupdates/issues/919`
=> update metadata search

plugin/_locales/en/messages.json, plugin/css/default.css, plugin/js/Library.js, plugin/js/UserPreferences.js, plugin/popup.html
This adds a new Library view that is toggable in the advanced Library options:
With a click on the cover the epub gets downloaded.
=> Add Library compact view

plugin/js/HttpClient.js
=> Handle HTTP 524 error

plugin/js/parsers/NoblemtlParser.js
=> add my-novel.online

plugin/js/parsers/VynovelParser.js, plugin/popup.html
=> Add vynovel.com

plugin/js/parsers/AppYoruWorldParser.js, plugin/popup.html
=> Add app.yoru.world

plugin/js/parsers/DaoDivineTlParser.js, plugin/js/parsers/LanrySpaceParser.js, plugin/popup.html
=> Add lanry.space

plugin/js/parsers/RandomtranslatorParser.js, plugin/popup.html
=> Add RrandomtranslatorParser

plugin/js/Library.js
=> Library better export/ import

plugin/js/parsers/ToctruyenParser.js, plugin/popup.html
=> Add ToctruyenParser

plugin/js/parsers/MadaraParser.js
Added Madara Variant for #1822. Included comment above for future debugging.
=> #1822 - fix greenztl2 chapter generation

plugin/js/parsers/NobadnovelParser.js, plugin/js/parsers/VelvetReverieParser.js, plugin/js/parsers/ZenithtlsParser.js, plugin/popup.html
references: #1833, #1837, #1819
=> Add parsers

plugin/js/Library.js, plugin/js/parsers/QidianParser.js
reference: #1840
web-ext lint results in:
=> fix firefox warning

plugin/js/parsers/ArchiveOfOurOwnParser.js, plugin/js/parsers/WtrlabParser.js
=> hotfix WtrlabParser 

plugin/js/Library.js
After a fix for #1842 it renders wrong
this pr changes it to the old look
=> Fix Library render

plugin/js/HttpClient.js
fixes the bad firefox fix. from #1857
=> declarativeNetRequest better security

plugin/js/parsers/TumblrParser.js
=> fix TumblrParser image problem

plugin/js/parsers/NoblemtlParser.js
reference: https://github.com/dteviot/WebToEpub/pull/1867#issuecomment-2845553786
=> update MyNovelOnlineParser fix firefox warning

plugin/js/parsers/SangtacvietParser.js, plugin/popup.html
reference: #1477
The site has an custom rate limit.
As i access the "api" directly i get an http 200 response but the body says solve the captcha.
How can i trigger the 429 error response from the parser? (line 71)
I think that this problem will be more widespread soon because at the moment most api's have no rate limit i don't think that this will last.https://github.com/dteviot/WebToEpub/issues/1468#issuecomment-2843609231
=> help needed Add SangtacvietParser

plugin/js/parsers/SangtacvietParser.js
=> Add sangtacviet.vip

plugin/js/parsers/ChosentwofanficParser.js, plugin/popup.html
=> Add ChosentwofanficParser

plugin/js/parsers/ShinningnoveltranslationsParser.js, plugin/popup.html
=> Add ShinningnoveltranslationsParser

plugin/js/parsers/BuntlsParser.js, plugin/popup.html
=> Add BuntlsParser

plugin/js/parsers/ChosentwofanficParser.js, plugin/js/parsers/LilyonthevalleyParser.js, plugin/popup.html
=> Add LilyonthevalleyParser

plugin/js/parsers/DarkstartranslationsParser.js, plugin/popup.html
=> Add DarkstartranslationsParser

package.json, plugin/js/parsers/HelheimscansParser.js, readme.md
=> Add site https://helioscans.com/

plugin/_locales/en/messages.json, plugin/js/Library.js, plugin/popup.html
reference: #1899, #1273
This adds the option in Library -> Show Advanced Library Options
To add a list of novel urls as a batch to be downloaded and added in the Library.
=> Add AddListToLibrary()

.github/workflows/node.js.yml, package.json
reference: #1901
There were a few issues in the past with warnings from mozilla. This will automatically check for these warnings in PR requests.
Most problematic contributor @gamebeaker ;)
=> update gihub actions web-ext

.gitignore, plugin/js/ChapterUrlsUI.js, plugin/js/ReadingList.js, plugin/js/parsers/ArchiveOfOurOwnParser.js, plugin/js/parsers/MadaraParser.js, plugin/js/parsers/TapasParser.js, unitTest/UtestLnmtlParser.js, unitTest/UtestQidianParser.js, unitTest/UtestRanobesParser.js
Any change that isn't in TapasParser, MadaraParser, or .gitignore was to fix a failing unit test.
=> Misc fixes

plugin/js/EpubPacker.js, plugin/js/Util.js, plugin/js/main.js, plugin/js/parsers/NovelinguaParser.js, plugin/js/parsers/TapasParser.js, plugin/popup.html, unitTest/UtestEpubPacker.js
Sorry for the PR spam. This one has the changes from my other un-merged PR plus more. I just have a lot of fixes and changes in my private repo and I've been trying to clean up what might be good for everyone, including parsers for sites that are being requested lately (like Novelingua).
My other PR could be closed or merged first and I can also remove anything that's not wanted.
=> Various fixes plus add novelingua

plugin/js/parsers/NovelinguaParser.js
Fixes issue with some chapters being empty.
=> Fix NovelinguaParser

package.json, plugin/_locales/en/messages.json, plugin/js/Parser.js, plugin/js/UserPreferences.js, plugin/popup.html, readme.md
=> Make removal of previous and next chapter hyperlinks toggleable

package.json, plugin/js/parsers/WetriedTlsParser.js, plugin/manifest.json, plugin/popup.html, readme.md
Reaperscans.com has been shut down due to a DMCA notice, and now they are updating chapters on the new site wetriedtls.com.
=> Add site WeTriedTls
